[package]
name = "vsync"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
display-link = { git = "https://github.com/U32Float/display-link" }
dashmap = "5.5.3"
